# Generated by Django 4.2.7 on 2024-03-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/jobhunt/")),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
                ("description", models.CharField(max_length=31)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("Inexperienced", "Inexperienced"),
                            ("Between 1 and 3 years", "Between 1 and 3 years"),
                            ("Between 3 and 6 years", "Between 3 and 6 years"),
                            ("More 6 years", "More 6 years"),
                            ("Unimportant", "Unimportant"),
                        ],
                        default="Inexperienced",
                        max_length=31,
                    ),
                ),
                (
                    "typeOfWork",
                    models.CharField(choices=[("OFF", "offline"), ("ON", "online")], default="OFF", max_length=7),
                ),
                (
                    "workingTime",
                    models.CharField(
                        choices=[("FULL", "Full time"), ("HALF", "Half day")], default="FULL", max_length=10
                    ),
                ),
                ("price_from", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("price_to", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("career", models.CharField(blank=True, max_length=31, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vacancies", to="taskbig_1.category"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="taskbig_1.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="taskbig_1.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
