# Generated by Django 4.2.7 on 2024-03-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taskbig_1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=7)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("expected_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_education", models.BooleanField(default=False)),
                ("is_have_experience", models.BooleanField(default=False)),
                ("is_have_foreign_language", models.BooleanField(default=False)),
                ("is_have_certification", models.BooleanField(default=False)),
                ("is_have_driver_license", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_category",
                        to="taskbig_1.category",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_district",
                        to="taskbig_1.district",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_region",
                        to="taskbig_1.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
