# Generated by Django 4.2.7 on 2024-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="title",
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
