# Generated by Django 4.2.7 on 2024-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_2", "0002_vacancy_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="salary",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_from",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_to",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
