# Generated by Django 4.2.7 on 2024-03-18 22:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=31)),
                ("surname", models.CharField(max_length=31)),
                ("date_of_birth", models.DateField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            managers=[
                ("user_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
